// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaSocket.Data;

#nullable disable

namespace PruebaSocket.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531234542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PruebaSocket.Models.Esp32Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceKey")
                        .IsUnique();

                    b.ToTable("Esp32Devices");
                });

            modelBuilder.Entity("PruebaSocket.Models.Esp32Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Response")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("SourceDeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetDeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("WasProcessed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SourceDeviceId");

                    b.HasIndex("TargetDeviceId");

                    b.ToTable("Esp32Messages");
                });

            modelBuilder.Entity("PruebaSocket.Models.Esp32Message", b =>
                {
                    b.HasOne("PruebaSocket.Models.Esp32Device", "SourceDevice")
                        .WithMany("SentMessages")
                        .HasForeignKey("SourceDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PruebaSocket.Models.Esp32Device", "TargetDevice")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("TargetDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceDevice");

                    b.Navigation("TargetDevice");
                });

            modelBuilder.Entity("PruebaSocket.Models.Esp32Device", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
